[package]
name = "dr_hack4dk"
version = "0.1.0"
authors = ["Polly Nielsen Boutet-Livoff <pollyboutet@gmail.com>"]

[dependencies]
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
tantivy = "0.4.3"
tempdir = "0.3.5"
